### PR TITLE
Clean up spacing issues and refactor common DT nodes

### PR DESCRIPTION
**Pull request by caksoylar**
Hi Darryl, I was looking through the config and encountered a few formatting issues and some duplicated config across two halves. The changes aren't intended to change anything functionally: Firmware files produced before and after these changes are nearly identical (there is a tiny diff that is likely related to linking order). However since I don't have v2 hardware I can't test to confirm.

The changes are split into three commits; happy to drop certain ones if not wanted. Hope it helps.

### CODE REVIEW

**Comment by caksoylar** [comment]
Added a new commit to remove settings from `*_defconfig` that are already set in `Kconfig.defconfig`.

**Comment by caksoylar** [comment]
This refactoring was tested by Gillesh/@kikangh from the Discord server, reportedly working correctly.

**Comment by Kikangh** [comment]
> This refactoring was tested by Gillesh/@kikangh from the Discord server, reportedly working correctly.

Yep. Everything I use is working properly as far as I can tell.

I can make some specific tests that would be required, just ask.

**Comment by caksoylar** [comment]
I also added back the default matrix transform to the `chosen` node in [5988902](https://github.com/LOWPROKB/zmk/pull/3/commits/5988902b5d65dd5b88a88dd65a3f5d60483706d8). While this is set in the keymap, I think it is good practice to have a default set in the board files, in case someone wants to write their keymap from scratch. If it is specified in the keymap it will always take priority over this one.

**Comment by caksoylar** [comment]
I think some of the spacing issues etc. were resolved in the branch already. @LOWPROKB let me know if you'd like me to rebase, I think at least the changes in [fa1f0d9](https://github.com/LOWPROKB/zmk/pull/3/commits/fa1f0d91d0d87f9e23b7b75f6591b72d40189a13), [22e1113](https://github.com/LOWPROKB/zmk/pull/3/commits/22e111334c5eeed0516d9c289f15e20152359188) and [5988902](https://github.com/LOWPROKB/zmk/pull/3/commits/5988902b5d65dd5b88a88dd65a3f5d60483706d8) might still be relevant.

**Pull request closed without merging**
